version: "3.8"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    env_file:
      - path: ../.env
        required: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SUBDOMAINS=${HOMESERVER_URL?err}
      - TOKEN=${DUCKDNS_TOKEN?err}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - ${STORAGE_PATH?err}/config/duckdns/config:/config
    restart: unless-stopped
    networks:
      - homeserver
networks:
  homeserver:
    name: homeserver
    external: true