version: "3.8"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - ./config/duckdns/config:/config
    restart: unless-stopped
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./config/nextcloud/config:/config
      - /mnt/merger/data:/data
    ports:
      - 9001:443
    depends_on:
      - nextcloud-db
    links:
      - nextcloud-db
    restart: unless-stopped
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    environment:
      MARIADB_ROOT_PASSWORD: ${NEXTCLOUD_DB_ROOT_PASSWORD}
    restart: unless-stopped
  #nextcloud:
  #jellyfin:
  #homeassistant: