services:
  duckdns:
    extends:
      file: services/duckdns.yml
      service: duckdns
  swag:
    extends:
      file: services/swag.yml
      service: swag
  nextcloud:
    extends:
      file: services/nextcloud.yml
      service: nextcloud
  homeassistant:
    extends:
      file: services/homeassistant.yml
      service: homeassistant
  jellyfin:
    extends:
      file: services/jellyfin.yml
      service: jellyfin
  nextcloud-postgres:
    extends:
      file: services/nextcloud-postgres.yml
      service: nextcloud-postgres
  wireguard:
    extends:
      file: services/wireguard.yml
      service: wireguard
  homepage:
    extends:
      file: services/homepage.yml
      service: homepage
  qbittorrent:
    extends:
      file: services/qbittorrent.yml
      service: qbittorrent
  syncthing:
    extends:
      file: services/syncthing.yml
      service: syncthing
networks:
  homeserver:
    name: homeserver
    external: true
