version: "3.8"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=${PUID?err}
      - PGID=${PGID?err}
      - TZ=${TZ?err}
      - SUBDOMAINS=${HOMESERVER_URL?err}
      - TOKEN=${DUCKDNS_TOKEN?err}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    labels:
    - homepage.group=Network
    - homepage.name=Duck DNS
    - homepage.icon=duckdns.svg
    - homepage.description=Duck DNS
    - homepage.siteMonitor=https://nishh.duckdns.org
    volumes:
      - ${CONFIG_PATH?err}/duckdns/config:/config
    restart: unless-stopped
    networks:
      - homeserver