version: "3.8"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SUBDOMAINS=${HOMESERVER_URL}
      - TOKEN=${DUCKDNS_TOKEN}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - ../config/duckdns/config:/config
    restart: unless-stopped
    networks:
      - homeserver
networks:
  homeserver:
    name: homeserver
    external: true