version: '3.8'
services:
  esphome:
    image: esphome/esphome
    container_name: esphome
    volumes:
      - ${CONFIG_PATH?err}/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    environment:
      - USERNAME=esphome
      - PASSWORD>:${ESPHOME_PASSWORD?err}
    labels:
      - homepage.group=Home Automation
      - homepage.name=ESP Home
      - homepage.icon=esphome.svg
      - homepage.href=https://esphome.nishh.duckdns.org
      - homepage.description=ESP Home
      - homepage.siteMonitor=https://esphome.nishh.duckdns.org
    ports:
      - 6052:6052
      - 6053:6053
    restart: unless-stopped
    networks:
      - homeserver
