version: '3'
services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ${CONFIG_PATH?err}/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    environment:
      - USERNAME=esphome
      - PASSWORD=${ESPHOME_PASSWORD?err}
    ports:
      - 6052:6052
    restart: unless-stopped
    networks:
      - homeserver