version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - PUID=${PUID?err}
      - PGID=${PGID?err}
      - TZ=${TZ?err}
    labels:
      - homepage.group=Home Automation
      - homepage.name=Home Assistant
      - homepage.icon=home-assistant.svg
      - homepage.href=https://homeassistant.nishh.duckdns.org
      - homepage.description=Home Assistant
      - homepage.siteMonitor=https://homeassistant.nishh.duckdns.org
    volumes:
      - ${CONFIG_PATH?err}/homeassistant/config:/config
    ports:
      - 8123:8123
    restart: unless-stopped
    networks:
      - homeserver