version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - PUID=${PUID?err}
      - PGID=${PGID?err}
      - TZ=${TZ?err}
    volumes:
      - ${CONFIG_PATH?err}/homeassistant/config:/config
    ports:
      - 9003:8123
    restart: unless-stopped
    networks:
      - homeserver