version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - JELLYFIN_PublishedServerUrl=${HOMESERVER_URL}
    volumes:
      - ../config/jellyfin/config:/config
      - /mnt/merger/data/__groupfolders/1:/data
    ports:
      - 9002:8096
    restart: unless-stopped
    networks:
      - homeserver
networks:
  homeserver:
    name: homeserver
    external: true