version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID?err}
      - PGID=${PGID?err}
      - TZ=${TZ?err}
      - JELLYFIN_PublishedServerUrl=${HOMESERVER_URL?err}
    volumes:
      - ${CONFIG_PATH?err}/jellyfin/config:/config
      - ${STORAGE_PATH?err}/media:/data/media
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - homeserver