version: "3.8"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PUID?err}
      - PGID=${PGID?err}
      - TZ=${TZ?err}
    labels:
      - homepage.group=Cloud
      - homepage.name=Nextcloud
      - homepage.icon=nextcloud.svg
      - homepage.href=https://nextcloud.nishh.duckdns.org
      - homepage.description=Nextcloud
      - homepage.siteMonitor=https://nextcloud.nishh.duckdns.org
    volumes:
      - ${CONFIG_PATH?err}/nextcloud/config:/config
      - ${STORAGE_PATH?err}/data:/data
    ports:
      - 9443:443
    restart: unless-stopped
    networks:
      - homeserver