version: "3.8"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PUID?err}
      - PGID=${PGID?err}
      - TZ=${TZ?err}
    volumes:
      - ${CONFIG_PATH?err}/nextcloud/config:/config
      - ${STORAGE_PATH?err}/data:/data
      - ${STORAGE_PATH?err}/media:/mnt/media
      - ${STORAGE_PATH?err}/syncthing:/mnt/syncthing
    ports:
      - 9443:443
    restart: unless-stopped
    networks:
      - homeserver