version: "3.8"
services:
  nextcloud-postgres:
    image: postgres:17
    container_name: nextcloud-postgres
    environment:
      POSTGRES_PASSWORD: ${NEXTCLOUD_POSTGRES_PASSWORD?err}
    volumes:
      - ${CONFIG_PATH?err}/nextcloud-postgres/data:/var/lib/postgresql/data
    ports:
      - 5501:5432
    restart: unless-stopped
    depends_on:
      - nextcloud-postgres
    networks:
      - homeserver