version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?err}
    labels:
      - homepage.group=Database
      - homepage.name=Postgres
      - homepage.icon=postgres.svg
    volumes:
      - ${CONFIG_PATH?err}/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - homeserver