version: "3.8"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID?err}
      - PGID=${PGID?err}
      - TZ=${TZ?err}
      - URL=${HOMESERVER_URL?err}
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN?err}
    labels:
      - homepage.group=Network
      - homepage.name=SWAG
      - homepage.icon=linuxserver-io.svg
      - homepage.href=https://nishh.duckdns.org
      - homepage.description=SWAG
      - homepage.siteMonitor=https://nishh.duckdns.org
    volumes:
      - ${CONFIG_PATH?err}/swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - homeserver