version: "3.8"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - URL=${HOMESERVER_URL}
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
    volumes:
      - ../config/swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - homeserver
networks:
  homeserver:
    name: homeserver
    external: true