version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?err}
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - homeserver