version: "3.8"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${STORAGE_PATH?err}/config/nextcloud/config:/config
      - ${STORAGE_PATH?err}/data:/data
    ports:
      - 9001:443
    restart: unless-stopped
    networks:
      - homeserver
networks:
  homeserver:
    name: homeserver
    external: true
env_file:
  - path: ../.env
    required: true